// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutogrowController from "./autogrow_controller"
application.register("autogrow", AutogrowController)

import ConfirmationController from "./confirmation_controller"
application.register("confirmation", ConfirmationController)

import CustomDateRangeController from "./custom_date_range_controller"
application.register("custom-date-range", CustomDateRangeController)

import DistanceShortcutsController from "./distance_shortcuts_controller"
application.register("distance-shortcuts", DistanceShortcutsController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FilterGenderController from "./filter_gender_controller"
application.register("filter-gender", FilterGenderController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import PinnedPagesMenuController from "./pinned_pages_menu_controller"
application.register("pinned-pages-menu", PinnedPagesMenuController)

import RestoreDefaultsController from "./restore_defaults_controller"
application.register("restore-defaults", RestoreDefaultsController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import SortTableController from "./sort_table_controller"
application.register("sort-table", SortTableController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TeamGenderFieldsController from "./team_gender_fields_controller"
application.register("team-gender-fields", TeamGenderFieldsController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
