databases:
  - name: postgres
    databaseName: pace_maker_production
    user: pace_maker
    plan: free

services:
  - type: web
    name: pace_maker
    runtime: ruby
    plan: free
    buildCommand: "..bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pace_maker_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
